# color constants
RED='\[\e[0;31m\]'
WHITE='\[\e[1;37m\]'
RESET='\[\e[0m\]'

### ENV variables ###

# look for commands in these places
export PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="$HOME/.bin:$PATH"

# dotfiles repo
export DOTFILES="$( cd "$( dirname "$( readlink ~/.bashrc )" )/.." && pwd )"

# shortened prompt that includes git branch info
source "$DOTFILES/git-prompt.sh"
export PS1="$RED\w$WHITE$(__git_ps1)$RED\$$RESET "

# update bash history after every command instead of waiting until the
# shell is closed
export PROMPT_COMMAND="history -a"

# expand bash history buffer
export HISTSIZE=1000000
export HISTFILESIZE=1000000

# make vim the default text editor
export EDITOR="vim"

### git ###

# setup git completion
source "$DOTFILES/git-completion.bash"

# make `g` behave like `git status` with no args, or `git` with args
g () {
  if [ $# -eq 0 ]
  then
    git status
  else
    git "$@"
  fi
}
__git_complete g _git

### other ###

# initialize rbenv
eval "$(rbenv init -)"

# initialize node version manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Load aliases
source "$DOTFILES/aliases"

# Load any local configuration
[[ -f ~/.bashrc.local ]] && source ~/.bashrc.local
