# color constants
RED='\[\e[0;31m\]'
WHITE='\[\e[1;37m\]'
RESET='\[\e[0m\]'

### ENV variables ###

# look for commands in these places
export PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="$HOME/.bin:$PATH"

# dotfiles repo
export AA_CONFIG_DIR="$(cat $HOME/.aa_config_dir)"

# shortened prompt that includes git branch info
source "$AA_CONFIG_DIR/git-prompt.sh"
export PS1="$RED\w$WHITE$(__git_ps1)$RED\$$RESET "

# update bash history after every command instead of waiting until the
# shell is closed
export PROMPT_COMMAND="history -a"

# expand bash history buffer
export HISTSIZE=1000000
export HISTFILESIZE=1000000

# make vim the default text editor
export EDITOR="vim"

### git ###

# setup git completion
source "$AA_CONFIG_DIR/git-completion.bash"

### other ###

# initialize rbenv
eval "$(rbenv init -)"

# initialize node version manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Load aliases
source "$AA_CONFIG_DIR/aliases"

# Load any local configuration
[[ -f "$HOME/.profile" ]] && source "$HOME/.profile"
