#!/bin/bash

# link dotfiles
ln -sf ~/.dotfiles/aliases ~/.aliases
ln -sf ~/.dotfiles/bashrc ~/.bashrc
ln -sf ~/.dotfiles/emacsrc ~/.emacsrc
ln -sf ~/.dotfiles/eslintrc ~/.eslintrc
ln -sf ~/.dotfiles/gemrc ~/.gemrc
ln -sf ~/.dotfiles/gitconfig ~/.gitconfig
ln -sf ~/.dotfiles/gitignore ~/.gitignore
ln -sf ~/.dotfiles/inputrc ~/.inputrc
ln -sf ~/.dotfiles/irbrc ~/.irbrc
ln -sf ~/.dotfiles/jshintrc ~/.jshintrc
ln -sf ~/.dotfiles/bash_profile ~/.bash_profile
ln -sf ~/.dotfiles/pryrc ~/.pryrc
ln -sf ~/.dotfiles/railsrc ~/.railsrc
ln -sf ~/.dotfiles/rdebugrc ~/.rdebugrc
ln -sf ~/.dotfiles/rspec ~/.rspec
ln -sf ~/.dotfiles/rubocop.yml ~/.rubocop.yml
ln -sf ~/.dotfiles/sqliterc ~/.sqliterc
# ln -sf ~/.dotfiles/vimrc ~/.vimrc
ln -sf ~/.dotfiles/shortcuts.png ~/Pictures/shortcuts.png
cp ~/.dotfiles/atom/config.cson ~/.atom/config.cson
